/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NcSideDrawer {
        "open": () => Promise<void>;
        "opened": boolean;
        "title": string;
    }
}
declare global {
    interface HTMLNcSideDrawerElement extends Components.NcSideDrawer, HTMLStencilElement {
    }
    var HTMLNcSideDrawerElement: {
        prototype: HTMLNcSideDrawerElement;
        new (): HTMLNcSideDrawerElement;
    };
    interface HTMLElementTagNameMap {
        "nc-side-drawer": HTMLNcSideDrawerElement;
    }
}
declare namespace LocalJSX {
    interface NcSideDrawer {
        "opened"?: boolean;
        "title"?: string;
    }
    interface IntrinsicElements {
        "nc-side-drawer": NcSideDrawer;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nc-side-drawer": LocalJSX.NcSideDrawer & JSXBase.HTMLAttributes<HTMLNcSideDrawerElement>;
        }
    }
}
