/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface NcStockPrice {
        "stockSymbol": string;
    }
}
declare global {
    interface HTMLNcStockPriceElement extends Components.NcStockPrice, HTMLStencilElement {
    }
    var HTMLNcStockPriceElement: {
        prototype: HTMLNcStockPriceElement;
        new (): HTMLNcStockPriceElement;
    };
    interface HTMLElementTagNameMap {
        "nc-stock-price": HTMLNcStockPriceElement;
    }
}
declare namespace LocalJSX {
    interface NcStockPrice {
        "stockSymbol"?: string;
    }
    interface IntrinsicElements {
        "nc-stock-price": NcStockPrice;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "nc-stock-price": LocalJSX.NcStockPrice & JSXBase.HTMLAttributes<HTMLNcStockPriceElement>;
        }
    }
}
